version: "3.8"

services:
  zomboid-dedicated-server:
    build:
      context: .
      dockerfile: docker/zomboid-dedicated-server.Dockerfile
    image: "docker.io/renegademaster/zomboid-dedicated-server:latest"
    container_name: zomboid
    restart: "unless-stopped"
    environment:
      - "ADMIN_PASSWORD=Ferritus"
      - "ADMIN_USERNAME=Latin"
      - "AUTOSAVE_INTERVAL=15"
      - "BIND_IP=0.0.0.0"
      - "DEFAULT_PORT=16261"
      - "GAME_VERSION=public"
      - "GC_CONFIG=ZGC"
      - "MAP_NAMES=Muldraugh, KY"
      - "MAX_PLAYERS=16"
      - "MAX_RAM=4096m"
      - "MOD_NAMES="
      - "MOD_WORKSHOP_IDS="
      - "PAUSE_ON_EMPTY=true"
      - "PUBLIC_SERVER=true"
      - "RCON_PASSWORD=Ferritus"
      - "RCON_PORT=27015"
      - "SERVER_NAME=NONDRG Cafeteria"
      - "SERVER_PASSWORD=RockNStone"
      - "STEAM_VAC=true"
      - "UDP_PORT=16262"
      - "USE_STEAM=true"
      - "TZ=UTC"
    ports:
      - "16261-16272:16261-16272/udp"
      - target: 27015
        published: 27015
        protocol: tcp
    volumes:
      - //D/DOCKER/Zomboid/DedicatedServer:/home/steam/ZomboidDedicatedServer
      - //D/DOCKER/Zomboid/ZomboidConfig:/home/steam/Zomboid/
